---
src-ci-repo: https://github.com/SUSE/cf-ci.git

src-rails-example-repo: https://github.com/scf-samples/rails-example.git
kube-pool-repo: git@github.com:SUSE/cf-ci-pools.git
kube-pool-key: *github-private-key
kube-pool-branch: azure-kube-hosts
kube-pool-pool: azure-kube-hosts

s3-config-endpoint: ~
s3-config-access-key: *aws-access-key
s3-config-secret-key: *aws-secret-key

s3-config-bucket-sles: cap-release-archives

s3-config-prefix-sidecars: brokers/

registry-hostname: *docker-internal-registry
registry-username: *docker-internal-username
registry-password: *docker-internal-password
organization: splatform

magic-dns-service: omg.howdoi.website

src-repo: SUSE/scf

status-email-host: *ci-status-email-host
status-email-port: *ci-status-email-port
status-email-username: *ci-status-email-username
status-email-password: *ci-status-email-password
status-email-sender: *ci-status-email-sender
status-email-receiver: *ci-status-email-receiver
