---
src-ci-repo: https://github.com/SUSE/cf-ci.git

src-rails-example-repo: https://github.com/scf-samples/rails-example.git
kube-pool-repo: git@github.com:SUSE/cf-ci-pools.git
kube-pool-key: *github-private-key

# Used by s3 resource for pulling latest RC
s3-config-endpoint: ~
s3-config-access-key: *aws-access-key
s3-config-secret-key: *aws-secret-key

s3-config-bucket-sles: scf-v3


registry-hostname: *docker-public-staging-registry
organization: *docker-public-staging-org

magic-dns-service: omg.howdoi.website

src-repo: SUSE/kubecf

cap-pre-upgrade-url: bundle-2.0-0aa03f3
cap-install-url: null

status-email-host: *ci-status-email-host
status-email-port: *ci-status-email-port
status-email-username: *ci-status-email-username
status-email-password: *ci-status-email-password
status-email-sender: *ci-status-email-sender
status-email-receiver: *ci-status-email-receiver

enable-autoscaler: false
enable-credhub: false
enable-external-uaa-scf-db: false

terraform-platforms: [gke, aks]
terraform-gke-location: us-west1-a
terraform-aks-location: eastus
