---
src-repo: https://github.com/SUSE/scf.git
src-branch: develop
src-ci-repo: https://github.com/SUSE/cf-ci.git
src-ci-branch: master

kube-pool-repo: git@github.com:SUSE/cf-ci-pools.git
kube-pool-key: *github-private-key
kube-pool-branch: van-kube-hosts
kube-pool-pool: van-kube-hosts

s3-config-endpoint: ~
s3-config-access-key: *aws-access-key
s3-config-secret-key: *aws-secret-key
s3-config-bucket-opensuse: cap-release-archives
s3-config-prefix-opensuse: master/
s3-config-bucket-sles: cap-release-archives
s3-config-prefix-sles: master/

registry-hostname: *docker-internal-registry
registry-username: *docker-internal-username
registry-password: *docker-internal-password
organization: splatform

magic-dns-service: omg.howdoi.website

cap-sle-url: https://s3.amazonaws.com/cap-release-archives/master/scf-sle-2.7.0%2Bcf1.9.0.0.g2d95fcb5.linux-amd64.zip
cap-opensuse-url: https://github.com/SUSE/scf/releases/download/2.7.0/scf-opensuse-2.7.0.cf1.9.0.0.g2d95fcb5.linux-amd64.zip
