#!/usr/bin/env bash

set -o errexit -o nounset

usage() {
    cat <<EOF

${0} [options] <feature-flags preset file>

The pipeline configuration file "qa-pipeline.yml" must exist.
The configuration file "config-<config variant>.yml" must exist.

Available options:
    -c, --config=       Config file that 
    -h, --help          Print this help and exit
    -p, --prefix=       Set additional pipeline prefix
    --pool=provo        Pool to take pool config and kube config from. Default is 'provo' 
    -t, --target=       Set fly target concourse

EOF
}

OPTS=$(getopt -o hp:t: --long help,pool:,prefix:,target: -- "$@")
eval set -- "${OPTS}"

pool=provo
prefix=""
target=""
secrets_file=""
while true ; do
    case "$1" in
        -h|--help)   usage ; exit 0 ;;
        -p|--prefix) prefix="${2%-}-" ; shift 2 ;;
        -t|--target) target="${2}" ; shift 2 ;;
        --pool)      pool="${2}" ; shift 2 ;;
        --)          shift ; break ;;
        *)           printf "Internal error: unexpected arguments %s\n" "$*" >&2 ; exit 1 ;;
    esac
done

if test -z "${1:-}" ; then
    usage
    exit 1
fi
pipeline_file="qa-pipeline.yml"
vars_file="config-${pool}.yml"
flags_file=${1}
pipeline_name=$(basename ${flags_file})
pipeline_name="${prefix}${pipeline_name%.yml}"


if ! test -r "${pipeline_file}" ; then
    usage >&2
    printf "Failed to read pipeline configuration %s\n" "${pipeline_file}" >&2
    exit 1
fi

if ! test -r "${vars_file}" ; then
    usage >&2
    if test -n "${1:-}" ; then
        printf "Variables file %s is not readable\n" "${vars_file}" >&2
    fi
    exit 1
fi

if ! test -r "${flags_file}" ; then
    usage >&2
    printf "Failed to read flags file %s\n" "${flags_file}" >&2
    exit 1
fi

if test -n "${CONCOURSE_SECRETS_FILE:-}"; then
    if test -r "${CONCOURSE_SECRETS_FILE:-}" ; then
        secrets_file="${CONCOURSE_SECRETS_FILE}"
    else
        printf "ERROR: Secrets file %s is not readable\n" "${CONCOURSE_SECRETS_FILE}" >&2
        exit 2
    fi
fi

fly \
    ${target:+"--target=${target}"} \
    set-pipeline \
    --pipeline="${pipeline_name}" \
    --config="${pipeline_file}" \
    --load-vars-from=<(
        # We concatenate the two vars files together so that the config vars can
        # refer to secret vars correctly
        ${secrets_file:+gpg --decrypt --batch ${secrets_file}} # Import secrets
        sed '/^---$/d' < "${vars_file}"                        # Config vars
        sed '/^---$/d' < "${flags_file}"
        ruby -r yaml << EOF | tail -n+2
          pipeline_flags=YAML.load_file('${flags_file}').keys
          all_flags=YAML.load_file('flags.yml').keys
          puts YAML.dump((all_flags - pipeline_flags).zip([false].cycle).to_h)
EOF
    )
fly \
    ${target:+"--target=$target"} \
    expose-pipeline \
    --pipeline="${pipeline_name}"
# fly \
#     ${target:+"--target=$target"} \
#     unpause-pipeline \
#     --pipeline="${pipeline_name}"
