# Concourse pipeline to run a single brain test

resources:
- name: ci
  type: git
  source:
    uri: ((src-ci-repo))
    branch: ((src-ci-branch))
    paths:
    - qa-pipelines/*
    - sample-apps/*

- name: s3.scf-config-sles
  type: s3
  source:
    endpoint: ((s3-config-endpoint))
    access_key_id: ((s3-config-access-key))
    secret_access_key: ((s3-config-secret-key))
    bucket: ((s3-config-bucket-sles))
    regexp: ((s3-config-prefix-sles))scf-sle-(.*)\.zip$

- name: pool.kube-hosts
  type: pool
  source:
    uri: ((kube-pool-repo))
    private_key: ((kube-pool-key))
    branch: ((kube-pool-branch))
    pool: ((kube-pool-pool))
jobs:
- name: ((pipeline-name))-001
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "001"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-002
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "002"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-003
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "003"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-004
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "004"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-005
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "005"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-006
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "006"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-007
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "007"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-008
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "008"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-009
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "009"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-010
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "010"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-011
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "011"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-012
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "012"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-013
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "013"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-014
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "014"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-015
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "015"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-016
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "016"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-017
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "017"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
- name: ((pipeline-name))-018
  plan:
  - do:
    - aggregate:
      - get: ci
      - get: s3.scf-config-sles
        trigger: true
      - put: pool.kube-hosts
        params: {acquire: true}
        timeout: 2m
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - do:
    - task: acceptance-tests-brain
      file: ci/qa-pipelines/tasks/run-test.yml
      params:
        ENABLE_CF_BRAIN_TESTS: true
        INCLUDE_BRAINS_REGEX: "018"
        GKE_PRIVATE_KEY_BASE64: ((gke-private-key-base64))
      input_mapping:
        s3.scf-config: s3.scf-config-sles
    - put: pool.kube-hosts
      params: {release: pool.kube-hosts}
