---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest
inputs:
- name: src
  path: go/src/github.com/square/certstrap
- name: ci
run:
  path: ci/certstrap/tasks/build.sh
outputs:
- name: out
