---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-orchestration
    tag: staging
inputs:
- name: ci
- name: s3.scf-config
- name: pool.kube-hosts
run:
  path: ci/helm-deploy-test/tasks/cf-deploy.sh
