---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-orchestration

params:
  KUBE_REGISTRY_HOSTNAME: ((kube-registry-hostname))
  KUBE_REGISTRY_USERNAME: ((kube-registry-username))
  KUBE_REGISTRY_PASSWORD: ((kube-registry-password))

inputs:
- name: ci
- name: s3.scf-config
- name: pool.kube-hosts
run:
  path: ci/helm-deploy-test/tasks/cf-deploy.sh
