---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-orchestration
    tag: staging
inputs:
- name: ci
outputs:
- name: scf-metrics
run:
  path: ci/helm-deploy-test/tasks/create-test-file.sh
