# Concourse pipeline to build deploy and teardown cf against a kube cluster

resources:
- name: ci
  type: git
  source:
    uri: ((src-ci-repo))
    branch: ((src-ci-branch))
    paths:
    - qa-pipelines/*

- name: s3.scf-config-opensuse
  type: s3
  source:
    endpoint: ((s3-config-endpoint))
    access_key_id: ((s3-config-access-key))
    secret_access_key: ((s3-config-secret-key))
    bucket: ((s3-config-bucket-opensuse))
    regexp: ((s3-config-prefix-opensuse))scf-opensuse-(.*).linux-amd64\.zip$

- name: s3.scf-config-sles
  type: s3
  source:
    endpoint: ((s3-config-endpoint))
    access_key_id: ((s3-config-access-key))
    secret_access_key: ((s3-config-secret-key))
    bucket: ((s3-config-bucket-sles))
    regexp: ((s3-config-prefix-sles))scf-sle-(.*).linux-amd64\.zip$

- name: pool.kube-hosts
  type: pool
  source:
    uri: ((kube-pool-repo))
    private_key: ((kube-pool-key))
    branch: ((kube-pool-branch))
    pool: ((kube-pool-pool))

jobs:
- name: helm-deploy-sa-test-openSUSE
  plan:
  - aggregate:
    - get: ci
    - get: s3.scf-config-opensuse
      trigger: true
    - put: pool.kube-hosts
      params: {acquire: true}
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - task: cf-deploy
    file: ci/qa-pipelines/tasks/cf-deploy.yml
    params:
      CAP_CHART: -opensuse
      HA: false
      MAGIC_DNS_SERVICE: ((magic-dns-service))
    input_mapping:
      s3.scf-config: s3.scf-config-opensuse
  - task: cf-smoke-tests
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: smoke-tests
      CAP_CHART: -opensuse
    input_mapping:
      s3.scf-config: s3.scf-config-opensuse
  - task: acceptance-tests-brain
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: acceptance-tests-brain
      CAP_CHART: -opensuse
    input_mapping:
      s3.scf-config: s3.scf-config-opensuse
  - task: acceptance-tests
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: acceptance-tests
      CAP_CHART: -opensuse
    input_mapping:
      s3.scf-config: s3.scf-config-opensuse
  # We intentionally don't put the teardown and pool release steps in an ensure
  # block, so that when tests fail we have a chance of examining why things are
  # failing.
  - task: cf-teardown
    file: ci/qa-pipelines/tasks/cf-teardown.yml
    timeout: 1h
  - put: pool.kube-hosts
    params: {release: pool.kube-hosts}

- name: helm-deploy-sa-test-SLES
  plan:
  - aggregate:
    - get: ci
    - get: s3.scf-config-sles
      trigger: true
    - put: pool.kube-hosts
      params: {acquire: true}
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - task: cf-deploy
    file: ci/qa-pipelines/tasks/cf-deploy.yml
    params:
      KUBE_REGISTRY_HOSTNAME: ((registry-hostname))
      KUBE_REGISTRY_USERNAME: ((registry-username))
      KUBE_REGISTRY_PASSWORD: ((registry-password))
      KUBE_ORGANIZATION: ((organization))
      CAP_CHART: ""
      HA: false
      MAGIC_DNS_SERVICE: ((magic-dns-service))
    input_mapping:
      s3.scf-config: s3.scf-config-sles
  - task: cf-smoke-tests
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: smoke-tests
      CAP_CHART: ""
    input_mapping:
      s3.scf-config: s3.scf-config-sles
  - task: acceptance-tests-brain
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: acceptance-tests-brain
      CAP_CHART: ""
    input_mapping:
      s3.scf-config: s3.scf-config-sles
  - task: acceptance-tests
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: acceptance-tests
      CAP_CHART: ""
    input_mapping:
      s3.scf-config: s3.scf-config-sles
  # We intentionally don't put the teardown and pool release steps in an ensure
  # block, so that when tests fail we have a chance of examining why things are
  # failing.
  - task: cf-teardown
    file: ci/qa-pipelines/tasks/cf-teardown.yml
    timeout: 1h
  - put: pool.kube-hosts
    params: {release: pool.kube-hosts}

- name: helm-deploy-ha-test-openSUSE
  plan:
  - aggregate:
    - get: ci
    - get: s3.scf-config-opensuse
      trigger: true
    - put: pool.kube-hosts
      params: {acquire: true}
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - task: cf-deploy
    file: ci/qa-pipelines/tasks/cf-deploy.yml
    params:
      CAP_CHART: -opensuse
      HA: true
      MAGIC_DNS_SERVICE: ((magic-dns-service))
    input_mapping:
      s3.scf-config: s3.scf-config-opensuse
  - task: cf-smoke-tests
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: smoke-tests
      CAP_CHART: -opensuse
    input_mapping:
      s3.scf-config: s3.scf-config-opensuse
  - task: acceptance-tests-brain
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: acceptance-tests-brain
      CAP_CHART: -opensuse
    input_mapping:
      s3.scf-config: s3.scf-config-opensuse
  - task: acceptance-tests
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: acceptance-tests
      CAP_CHART: -opensuse
    input_mapping:
      s3.scf-config: s3.scf-config-opensuse
  # We intentionally don't put the teardown and pool release steps in an ensure
  # block, so that when tests fail we have a chance of examining why things are
  # failing.
  - task: cf-teardown
    file: ci/qa-pipelines/tasks/cf-teardown.yml
    timeout: 1h
  - put: pool.kube-hosts
    params: {release: pool.kube-hosts}

- name: helm-deploy-ha-test-SLES
  plan:
  - aggregate:
    - get: ci
    - get: s3.scf-config-sles
      trigger: true
    - put: pool.kube-hosts
      params: {acquire: true}
    on_failure:
      put: pool.kube-hosts
      params: {release: pool.kube-hosts}
  - task: cf-deploy
    file: ci/qa-pipelines/tasks/cf-deploy.yml
    params:
      KUBE_REGISTRY_HOSTNAME: ((registry-hostname))
      KUBE_REGISTRY_USERNAME: ((registry-username))
      KUBE_REGISTRY_PASSWORD: ((registry-password))
      KUBE_ORGANIZATION: ((organization))
      CAP_CHART: ""
      HA: true
      MAGIC_DNS_SERVICE: ((magic-dns-service))
    input_mapping:
      s3.scf-config: s3.scf-config-sles
  - task: cf-smoke-tests
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: smoke-tests
      CAP_CHART: ""
    input_mapping:
      s3.scf-config: s3.scf-config-sles
  - task: acceptance-tests-brain
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: acceptance-tests-brain
      CAP_CHART: ""
    input_mapping:
      s3.scf-config: s3.scf-config-sles
  - task: acceptance-tests
    file: ci/qa-pipelines/tasks/run-test.yml
    params:
      TEST_NAME: acceptance-tests
      CAP_CHART: ""
    input_mapping:
      s3.scf-config: s3.scf-config-sles
  # We intentionally don't put the teardown and pool release steps in an ensure
  # block, so that when tests fail we have a chance of examining why things are
  # failing.
  - task: cf-teardown
    file: ci/qa-pipelines/tasks/cf-teardown.yml
    timeout: 1h
  - put: pool.kube-hosts
    params: {release: pool.kube-hosts}
