---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cap:clusterrolebinding:tests
roleRef:
  kind: ClusterRole
  name: suse:cap:psp:privileged
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: default
  namespace: stratos
- kind: ServiceAccount
  name: default
  namespace: pg-sidecar
- kind: ServiceAccount
  name: default
  namespace: mysql-sidecar
- kind: ServiceAccount
  name: test-brain
  namespace: scf
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: cap:clusterrolebinding:brains
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io
subjects:
- kind: ServiceAccount
  name: test-brain
  namespace: scf
