---
src-repo: https://github.com/SUSE/scf.git
src-branch: develop
src-ci-repo: https://github.com/SUSE/cf-ci.git
src-ci-branch: master

kube-pool-repo: git@github.com:SUSE/cf-ci-pools.git
kube-pool-key: *github-private-key
kube-pool-branch: k8s-hosts
kube-pool-pool: k8s-hosts

s3-config-endpoint: ~
s3-config-access-key: *aws-access-key
s3-config-secret-key: *aws-secret-key
s3-config-bucket: cf-opensusefs2
s3-config-prefix: scf/config/
