# Concourse pipeline to build deploy and teardown cf against a kube cluster
groups: []

resources:
- name: ci
  type: git
  source:
    uri: https://github.com/SUSE/cf-ci.git
    #branch: master
    branch: cf-deploy-teardown
    paths:
    - cf-deploy-teardown/*

- name: s3.scf-kube-yml
  type: s3
  source:
    access_key_id: {{s3-access-key}}
    bucket: kube-dist
    endpoint: {{s3-endpoint}}
    regexp: scf-kube-(.*).zip$
    secret_access_key: {{s3-secret-key}}
    private: true

jobs:
- name: cf-deploy-teardown
  plan:
  - aggregate:

    - get: ci
      trigger: true

    - get: s3.scf-kube-yml
      trigger: true

  - task: cf-deploy
    file: ci/cf-deploy-teardown/tasks/cf-deploy.yml
    params:
      K8S_HOST_IP: {{k8s-host-ip}}
      K8S_HOSTNAME: {{k8s-hostname}}
      K8S_USER: {{k8s-host-user}}
      K8S_PASSWORD: {{k8s-host-password}}

    
