# Concourse pipeline to build deploy and teardown cf against a kube cluster
groups: []

resources:
- name: ci
  type: git
  source:
    uri: https://github.com/SUSE/cf-ci.git
    branch: cf-deploy-teardown
    paths:
    - cf-deploy-teardown/*

- name: s3.uaa-kube-yml
  type: s3
  source:
    access_key_id: {{s3-access-key}}
    bucket: kube-config
    endpoint: {{s3-endpoint}}
    regexp: uaa-kube-(.*).zip$
    secret_access_key: {{s3-secret-key}}
    private: true

- name: s3.hcf-kube-yml
  type: s3
  source:
    access_key_id: {{s3-access-key}}
    bucket: kube-config
    endpoint: {{s3-endpoint}}
    regexp: hcf-kube-(.*).zip$
    secret_access_key: {{s3-secret-key}}
    private: true

jobs:
- name: cf-deploy-teardown
  plan:
  - aggregate:

    - get: ci
      trigger: true

    - get: s3.uaa-kube-yml
      trigger: true

    - get: s3.hcf-kube-yml
      trigger: true

  - task: cf-deploy
    file: ci/cf-deploy-teardown/tasks/cf-deploy.yml

    
