# Concourse pipeline to build opensuse-kubectl docker image
---
resources:
- name: ci
  type: git
  source:
    uri: https://github.com/SUSE/cf-ci.git
    #branch: master
    branch: cf-deploy-teardown
    paths:
    - opensuse-kubectl-docker/*

- name: docker.opensuse-kubectl-docker
  type: docker-image
  source:
    #repository: splatform/opensuse-kubectl
    repository: prabalsuse/opensuse-kubectl
    username: {{docker-username}}
    password: {{docker-password}}

jobs:
- name: build-image
  plan:
  - get: ci
    trigger: true
  - put: docker.opensuse-kubectl-docker
    params:
      build: ci/opensuse-kubectl-docker/dockerfiles
      dockerfile: ci/dockerfiles/opensuse-kubectl.dockerfile
