---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1'
inputs:
  - name: src
    path: src/github.com/SUSE/cf-usb-plugin
  - name: src-ci
run:
  path: src-ci/scripts/vet.sh
