---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-orchestration

inputs:
- name: ci
- name: s3.scf-config.linux
- name: pool.kube-hosts
run:
  path: ci/kube-deploy-test/tasks/cf-deploy.sh
