---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: latest
inputs:
- name: src
  path: src/github.com/SUSE/cf-usb-sidecar
- name: generated
- name: ci
outputs:
- name: out
run:
  path: ci/cf-usb/tasks/csm-build.sh
