---
src-repo: git@github.com:SUSE/scf.git
src-branch: develop
src-ci-repo: git@github.com:SUSE/cf-ci.git
src-ci-branch: master

dockerhub-registry: ~
dockerhub-org: splatform

manual-pull-sources: false

job-limit-repo: git@github.com:SUSE/cf-ci-pools.git
job-limit-branch: scf-deploy
job-limit-pool: scf-deploy

# Binaries built elsewhere
s3-fissile-endpoint: ~
s3-fissile-access-key: *aws-access-key
s3-fissile-secret-key: *aws-secret-key
s3-fissile-bucket: cf-opensusefs2
s3-fissile-prefix: fissile/
s3-stampy-endpoint: *s3-endpoint
s3-stampy-access-key: *s3-access-key
s3-stampy-secret-key: *s3-secret-key
s3-stampy-bucket: stampy
s3-stampy-prefix: ""
s3-certstrap-endpoint: ~
s3-certstrap-access-key: *aws-access-key
s3-certstrap-secret-key: *aws-secret-key
s3-certstrap-bucket: cf-opensusefs2
s3-certstrap-prefix: certstrap/

# Files we generate
s3-bucket: cf-opensusefs2
s3-kube-bucket: *s3-bucket
s3-helm-bucket: *s3-bucket
s3-endpoint: ~
s3-release-prefix: scf/releases/
s3-kube-prefix: scf/kube/
s3-helm-prefix: scf/helm/
s3-access-key: "{{aws-access-key}}"
s3-secret-key: "{{aws-secret-key}}"
