---
src-repo: git@github.com:SUSE/scf.git
src-branch: develop
src-ci-repo: git@github.com:SUSE/cf-ci.git
src-ci-branch: master

dockerhub-registry: ~
dockerhub-org: splatform

manual-pull-sources: false

job-limit-repo: ~
job-limit-branch: ~
job-limit-pool: ~

s3-fissile-bucket: cf-opensusefs2
s3-bucket: cf-opensusefs2
s3-endpoint: ~
s3-release-prefix: scf/releases/
s3-access-key: "{{aws-access-key}}"
s3-secret-key: "{{aws-secret-key}}"
