src-repo: https://github.com/SUSE/cf-usb-sidecar.git
src-branch: develop

ci-repo: https://github.com/SUSE/cf-ci.git
ci-branch: master

docker-tag: latest
docker-server: "staging.registry.howdoi.website/"
docker-username: *docker-internal-username
docker-password: *docker-internal-password

docker-cert-domain: unused.invalid
docker-cert-ca: ~

buildbase-base-image: opensuse:latest
buildbase-repo-cloud-tools: obs://Cloud:Tools
buildbase-repo-devel-languages-go: obs://devel:languages:go
buildbase-repo-extra: ""

s3-endpoint: ~
s3-access-key: *aws-access-key
s3-secret-key: *aws-secret-key
s3-bucket: cap-release-archives
s3-prefix: brokers/
s3-disable-ssl: false

# For publishing
charts-release-tool-url: *cap-release-tool-url
charts-github-org: SUSE
charts-github-username: *github-username
charts-github-access-token: *github-acces-token
charts-github-private-key: *github-private-key

# Commit sources to obs
commit-sources: false
