---
platform: linux
image_resource:
 type: docker-image
 source:
   repository: splatform/bosh-cli
inputs:
  - name: src
  - name: ci
run:
  path: ci/cf/tasks/create-release.sh
outputs:
  - name: out
