ci-repo: https://github.com/suse/cf-ci
ci-branch: develop
build-image-resource-repo: https://github.com/concourse/docker-image-resource
build-image-resource-branch: master
external-releases-yaml: kubecf-build-pipelines/external-releases/external-releases.yml
fissile-linux-s3-bucket: cf-opensusefs2
stemcell-repository: splatform/fissile-stemcell-sle
stemcell-version: SLE_15_SP1-23.8
registry-name: docker.io
registry-org: *docker-cfcontainerization-org
registry-user: *docker-cfcontainerization-username
registry-pass: *docker-cfcontainerization-password
s3-access-key: *aws-capbot-access-key
s3-secret-key: *aws-capbot-secret-key
github-access-token: *github-access-token
