---
  platform: linux
  image_resource:
    type: docker-image
    source:
      repository: splatform/cf-ci-orchestration
  inputs:
  - name: ci
  - name: sources
  params:
    AWS_ACCESS_KEY_ID: ~
    AWS_SECRET_ACCESS_KEY: ~
    BUCKET: ~
  run:
    path: ci/kubecf-build-pipelines/external-releases/tasks/push_sources.sh
