---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: golang
    tag: '1'
inputs:
- name: src
- name: src-ci
outputs:
- name: minibroker
run:
  path: src-ci/minibroker/scripts/build-minibroker.sh
