---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/helm-client
inputs:
- name: src
- name: src-ci
outputs:
- name: chart
run:
  path: src-ci/minibroker/scripts/generate-minibroker-chart.sh
