---
resources:
- name: src
  type: git
  source:
    uri: ((src-repo))
    private_key: ((src-private-key))
    branch: ((src-branch))

- name: ci
  type: git
  source:
    uri: ((src-ci-repo))
    private_key: ((src-ci-private-key))
    branch: ((src-ci-branch))

- name: s3.certstrap-binary
  type: s3
  source:
    endpoint: ((s3-certstrap-binary-endpoint))
    access_key_id: ((s3-certstrap-binary-access-key))
    secret_access_key: ((s3-certstrap-binary-secret-key))
    bucket: ((s3-certstrap-bucket))
    regexp: ((s3-certstrap-prefix))certstrap-(.*)\.tgz

jobs:
- name: build
  plan:
  - aggregate:
    - get: src
      trigger: true
    - get: ci
  - task: build
    file: ci/certstrap/tasks/build.yml
  - put: s3.certstrap-binary
    params:
      file: out/certstrap-*.tgz
