---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-orchestration
    tag: latest
inputs:
- name: ci
- name: s3.scf-config
- name: pool.kube-hosts

params:
  KUBE_REGISTRY_HOSTNAME: ""
  KUBE_REGISTRY_USERNAME: ""
  KUBE_REGISTRY_PASSWORD: ""
  KUBE_ORGANIZATION: ""
  HA: false # true, false, or "scaled"
  MAGIC_DNS_SERVICE: xip.io
  CAP_BUNDLE_URL: "https://s3.amazonaws.com/cap-release-archives/master/scf-sle-2.17.1%2Bcf7.11.0.4.ga6c993eb.zip"

run:
  path: ci/qa-pipelines/tasks/cf-deploy.sh
