---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-orchestration
    tag: cap2
inputs:
- name: ci
- name: meta
- name: s3.scf-config
- name: pool.kube-hosts
- name: commit-id
outputs:
- name: klog

params:
  KUBE_REGISTRY_HOSTNAME: ""
  KUBE_ORGANIZATION: ""
  HA: false # true, false, or "scaled"
  MAGIC_DNS_SERVICE: xip.io
  CAP_BUNDLE_URL: ""
  AZ_SP_APPID: ""
  AZ_SP_PASSWORD: ""
  AZ_SP_TENANT: ""
  AWS_ACCESS_KEY_ID: ""
  AWS_SECRET_ACCESS_KEY: ""
  GKE_PRIVATE_KEY_BASE64: ""
  KLOG_COLLECTION_ON_FAILURE: false
  #EMBEDDED_UAA: false # true or false
  ENABLE_CREDHUB: true
  ENABLE_AUTOSCALER: true
  EXTERNAL_DB: false # true or false

run:
  path: ci/qa-pipelines/tasks/cf-deploy.sh
