---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-orchestration
    tag: latest
inputs:
- name: ci
- name: s3.archive
outputs:
- name: commit-id
run:
  path: ci/qa-pipelines/tasks/cf-get-commit-id-test.sh
