---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-orchestration
    tag: prabal-terraform
inputs:
- name: ci
- name: pool.kube-hosts

params:
  KUBE_REGISTRY_HOSTNAME: ""
  KUBE_REGISTRY_USERNAME: ""
  KUBE_REGISTRY_PASSWORD: ""
  KUBE_ORGANIZATION: ""
  HA: false # true, false, or "scaled"
  MAGIC_DNS_SERVICE: xip.io
  CAP_BUNDLE_URL: ""

run:
  path: ci/qa-pipelines/tasks/delete-aks-resource-group.sh
