---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/cf-ci-orchestration
    tag: prabal-terraform
inputs:
- name: ci
#- name: cf-ci-pools
outputs:
- name: kubeconfig-pool
  path: kubeconfig-pool

params:
  KUBE_REGISTRY_HOSTNAME: ""
  KUBE_REGISTRY_USERNAME: ""
  KUBE_REGISTRY_PASSWORD: ""
  KUBE_ORGANIZATION: ""
  HA: false # true, false, or "scaled"
  MAGIC_DNS_SERVICE: xip.io
  CAP_BUNDLE_URL: ""

run:
  path: ci/qa-pipelines/tasks/terraform-deploy.sh
