---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: cfcontainerization/base-ci
    tag: latest
inputs:
- name: ci
- name: docker-image-resource
- name: cf-deployment
- name: scf
- name: s3.stemcell-version
- name: s3.fissile-linux
params:
  STEMCELL_OS: ~
  STEMCELL_REPOSITORY: ~
  STEMCELL_VERSIONED_FILE: ~
  CF_DEPLOYMENT_YAML: ~
  BOSH_CLI_TAG: ~
  SCF_OPS_SET_SUSE_BUILDPACKS: ~
  DOCKER_REGISTRY: ~
  DOCKER_ORGANIZATION: ~
  DOCKER_TEAM_USERNAME: ~
  DOCKER_TEAM_PASSWORD_RW: ~
run:
  path: ci/build-pipelines/release-images-cf-deployment/tasks/build.sh
