kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: nfsclaim
  annotations:
    volume.beta.kubernetes.io/storage-class: "persistent"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Mi
