---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: registry.suse.com/cap-staging/cf-ci
    tag: kubecf
inputs:
- name: ci
- name: s3.stemcell-version
- name: s3.fissile-linux
- name: gh_release
params:
  STEMCELL_REPOSITORY: ~
  STEMCELL_VERSIONED_FILE: ~
  REGISTRY_NAME: ~
  REGISTRY_ORG: ~
  REGISTRY_USER: ~
  REGISTRY_PASS: ~
  RELEASE_NAME: ~
run:
  path: ci/kubecf-build-pipelines/buildpacks/tasks/build.sh
