---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/base-ci
    tag: kubecf
inputs:
- name: ci
- name: docker-image-resource
- name: cf-deployment
- name: s3.stemcell-version
- name: s3.fissile-linux
params:
  STEMCELL_REPOSITORY: ~
  STEMCELL_VERSIONED_FILE: ~
  CF_DEPLOYMENT_YAML: ~
  REGISTRY_NAME: ~
  REGISTRY_ORG: ~
  REGISTRY_USER: ~
  REGISTRY_PASS: ~
run:
  path: ci/kubecf-build-pipelines/release-images-cf-deployment/tasks/build.sh
