# Production configuration for the cf-usb-plugin pipelines
# Note that the secrets are not here; they are in $CONCOURSE_SECRETS_FILE

upstream: cloudfoundry/cli-plugin-repo

src-owner:                   SUSE
src-repo:                         cf-usb-plugin
src-name:                    SUSE/cf-usb-plugin
src-repo-ref: git@github.com:SUSE/cf-usb-plugin.git
src-branch: develop

ci-repo: https://github.com/SUSE/cf-ci.git
ci-branch: master

s3-endpoint: ~
s3-access-key: *aws-access-key
s3-secret-key: *aws-secret-key
s3-bucket: suse-cf-usb-plugin
s3-prefix: /
s3-disable-ssl: false
