---
resources:
- name: src-ci-docker
  type: git
  source:
    uri: ((ci-repo))
    branch: ((ci-branch))
    private_key: ((github-private-key))
    paths:
    - minibroker/Dockerfile

- name: docker.helm-client
  type: docker-image
  source:
    repository: ((docker-org))/helm-client
    username: ((docker-username))
    password: ((docker-password))

groups:
- name: docker
  jobs:
  - build-docker-image

jobs:
- name: build-docker-image
  serial: true
  plan:
  - get: src-ci-docker
    trigger: true
  - put: docker.helm-client
    params:
      build: src-ci-docker/minibroker
      build_args:
        HELM_VERSION: ((helm-version))
