# Concourse pipeline to build deploy and teardown cf against a kube cluster

resources:
- name: cf-ci
  type: git
  source:
    uri: https://github.com/SUSE/cf-ci.git
    #branch: master
    branch: prabal-helm-deploy-test
    paths:
    - kube-deploy-test/*

- name: s3.scf-config.linux
  type: s3
  source:
    access_key_id: {{aws-access-key}}
    secret_access_key: {{aws-secret-key}}
    bucket: cf-opensusefs2
    regexp: config/scf-linux-amd64-(.*).zip$

- name: pool.k8s-hosts
  type: pool
  source:
    uri: git@github.com:SUSE/cf-ci-pools.git
    private_key: {{github-private-key}}
    branch: k8s-hosts
    pool: k8s-hosts

jobs:
- name: kube-deploy-test
  plan:
  - aggregate:
    - get: cf-ci
      trigger: true
    - get: s3.scf-config.linux
      trigger: true
    - put: pool.k8s-hosts
      params: {acquire: true}
  - task: cf-deploy
    file: cf-ci/kube-deploy-test/tasks/cf-deploy.yml
  - task: cf-smoke-tests
    file: cf-ci/kube-deploy-test/tasks/smoke-tests.yml
  - task: acceptance-tests-brain
    file: cf-ci/kube-deploy-test/tasks/acceptance-tests-brain.yml
  - task: acceptance-tests
    file: cf-ci/kube-deploy-test/tasks/acceptance-tests.yml
  - task: cf-teardown
    file: cf-ci/kube-deploy-test/tasks/cf-teardown.yml
  - put: pool.k8s-hosts
    params: {release: pool.k8s-hosts}
