cf-deployment-tags:
  - v8.0.0
  - v9.2.0
  - v9.5.0
  - v12.18.0
  - v12.36.0
  - v12.39.0
  - v12.40.0
  - v13.9.0
  - v13.17.0
ci-repo: https://github.com/suse/cf-ci
ci-branch: develop
build-image-resource-repo: https://github.com/concourse/docker-image-resource	
build-image-resource-branch: master
cf-deployment-repo: https://github.com/cloudfoundry/cf-deployment
cf-deployment-branch: master
cf-deployment-yaml: cf-deployment/cf-deployment.yml
fissile-linux-s3-bucket: cf-opensusefs2
stemcell-repository: splatform/fissile-stemcell-sle
stemcell-versions-s3-bucket: cf-operators
stemcell-version-file: fissile-stemcell-versions/fissile-stemcell-sle15-version
stemcell-s3-bucket-region: us-east-1
registry-name: docker.io
registry-org: *docker-cfcontainerization-org
registry-user: *docker-cfcontainerization-username
registry-pass: *docker-cfcontainerization-password
s3-access-key: *aws-capbot-access-key
s3-secret-key: *aws-capbot-secret-key
