---
platform: linux
image_resource:
  type: docker-image
  source:
    repository: splatform/base-ci
    tag: kubecf
inputs:
- name: ci
- name: s3.stemcell-version
- name: s3.fissile-linux
- name: kubecf
params:
  GITHUB_TOKEN: ~
  GITHUB_PRIVATE_KEY: ~
  GIT_MAIL: ~
  GIT_USER: ~
  STEMCELL_VERSIONED_FILE: ~
  KUBECF_VALUES: ~
  KUBECF_BRANCH: ~
run:
  path: ci/kubecf-build-pipelines/stemcell-bump/tasks/create_pr.sh
