# Concourse pipeline to build opensuse-cf-ci docker image
---
resources:
- name: cf-ci
  type: git
  source:
    uri: https://github.com/SUSE/cf-ci.git
    branch: master
    paths:
    - opensuse-cf-ci-docker/*

- name: docker.opensuse-cf-ci
  type: docker-image
  source:
    repository: splatform/opensuse-cf-ci
    username: {{docker-username}}
    password: {{docker-password}}

jobs:
- name: build-image
  plan:
  - get: cf-ci
    trigger: true
  - put: docker.opensuse-cf-ci
    params:
      build: cf-ci/opensuse-cf-ci-docker/
    get_params:
      skip_download: true
